model:
  class: model.zoo.samwise.Samwise
  params:
    image_shape: [3, 256, 256]
    width: 8
    enc_depth: 5
    aux_depth: 3
    wide: false
    reduce: max-mean
    rnn_dim: 64
    p_emb_drop: 0.2
    p_out_drop: 0.2
