model:
  class: model.zoo.senya.SenyaGanjubas
  params:
    image_shape: [3, 256, 256]
    width: 8
    enc_depth: 5
    aux_depth: 3
    wide: false
    rnn_dim: 128
    p_emb_drop: 0.0
    p_out_drop: 0.2
    enc_att: [2]
    dec_att: [2]
    aux_att: []
