defaults:
  - lr_schedule: one-cycle
  - common_transforms

general:
  gpu: 1

data:
  train:
    type: hdf5
    dir: /media/dmitry/other/dfdc-crops/hdf5
    chunks: 5 - 50
    dir_list: ''
    sample:
      frames: 10
      real_fake_ratio: 3.33
      sparse_frames_prob: 0.75
    loader:
      batch_size: 16
      workers: 1
  val:
    type: images
    dir: /media/dmitry/other/dfdc-crops/webp_lossy
    chunks: 0, 1, 2, 3, 4
    sample:
      frames: 10
      real_fake_ratio: 3.33
      sparse_frames_prob: 1.0
    loader:
      batch_size: 16
      workers: 1

model:
  img_size: 256
  enc_depth: 5
  enc_width: 8
  mid_layers: [128, 128]
  out_ch: 128

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0

train:
  epochs: 3
  epoch_length: 30
  checkpoints:
    interval_epoch: 5
    interval_iteration: 2000

validate:
  interval: 1

logging:
  log_iter_interval: 5
