defaults:
  - model: bilbo_defaults
  - lr_schedule: one-cycle
  - common_transforms

general:
  gpu: 1

data:
  train:
    type: hdf5
    dir: /media/dmitry/other/dfdc-crops/hdf5
    chunks: 5 - 50
    dir_list: ''
    sample:
      frames: 10
      real_fake_ratio: 3.33
      sparse_frames_prob: 0.5
    loader:
      batch_size: 16
      workers: 1
  val:
    type: hdf5
    dir: /media/dmitry/other/dfdc-crops/hdf5
    chunks: 0, 1, 2, 3, 4
    sample:
      frames: 10
      real_fake_ratio: 3.33
      sparse_frames_prob: 1.0
    loader:
      batch_size: 16
      workers: 1

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0

train:
  epochs: 3
  epoch_length: -1
  checkpoints:
    interval_epoch: 1
    interval_iteration: 1000

validate:
  interval: 1

logging:
  log_iter_interval: 100
