hydra:
  run:
    dir: /media/dmitry/data/predicts/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - data: default
  - model: samwise

general:
  gpu: 1
  seed: 333

data:
  test:
    type: video
    dir: /media/dmitry/data/dfdc-videos
    chunks: 0, 1, 2, 3, 4
    sample:
      frames: 10
      real_fake_ratio: 3.33
      sparse_frames_prob: 1.0
    loader:
      batch_size: 16
      workers: 1

model:
  weights: /media/dmitry/data/outputs/2020-03-23/11-54-19/checkpoint_7500_fixed.pth