hydra:
  run:
    dir: /media/dmitry/data/predicts/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - data: default
  - model: samwise

general:
  seed: 333
  save_dir: null
  csv_name: submission.csv

data:
  test:
    type: video # just a hint, no effect
    dir: /media/dmitry/data/dfdc-videos/dfdc_train_part_37
    max_open_files: 300
    sample:
      frames: 10
      stride: 30
      num_pass: 1
    loader:
      batch_size: 1
      workers: 1

face-detection:
  encoder: mnet
  weights: /home/dmitry/projects/dfdc/data/weights/mobilenet0.25_Final.pth
  batch_size: 64
  score_thresh: 0.75
  score_thresh_step: 0.05
  score_thresh_min: 0.5
  min_positive_rate: 0.6
  nms_thresh: 0.4
  top_k: 500
  keep_top_k: 5
  max_face_num_thresh: 0.25

model:
  class: model.zoo.samwise.Samwise
  params:
    image_shape: [3, 256, 256]
    width: 8
    enc_depth: 5
    aux_depth: 3
    wide: false
    reduce: max-mean
    rnn_dim: 64
    p_emb_drop: 0.2
    p_out_drop: 0.2
    train: false
  weights: /media/dmitry/data/outputs/2020-03-23/11-54-19/checkpoint_7500_fixed.pth
