hydra:
  run:
    dir: /media/dmitry/data/predicts/${now:%Y-%m-%d}/${now:%H-%M-%S}

general:
  seed: 333
  save_dir: null
  csv_name: submission.csv

data:
  test:
    type: video # just a hint, no effect
    dir: /media/dmitry/data/dfdc-videos/dfdc_train_part_38
    max_open_files: 300
    sample:
      frames: 10
      stride: 30
      num_pass: 1
      max_samples: 20
    loader:
      batch_size: 1
      workers: 1
    transforms:
      - transform:
          class: dataset.transforms.ResizeTensor
          params:
            size: 300
            mode: bicubic
            normalize: true
      - transform:
          class: torchvision.transforms.Normalize
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

face-detection:
  encoder: mnet
  weights: /home/dmitry/projects/dfdc/data/weights/mobilenet0.25_Final.pth
  batch_size: 32
  score_thresh: 0.75
  score_thresh_step: 0.05
  score_thresh_min: 0.5
  min_positive_rate: 0.6
  nms_thresh: 0.4
  top_k: 500
  keep_top_k: 5
  max_face_num_thresh: 0.25

model:
  class: model.zoo.efficient_kek.EfficientKek
  params:
    bb: tf_efficientnet_b3_ns
    bb_weights: null
    rnn_out: 256
    p_embed: 0.1
    p_input: 0.5
    p_out: 0.2
  weights: /media/dmitry/data/outputs/2020-03-31/16-27-17/checkpoint_4000.pth
