hydra:
  run:
    dir: /dfdc/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    handlers:
      file:
        filename: ${hydra.job.name}.log

defaults:
  - data: no_resize
  - model: encoder_tpu
  - loss: forensic-transfer
  - lr_scheduler: one-cycle
  - optimizer: adam_w

general:
  gpu: 0
  seed: 333

distributed:
  backend: null
  local_rank: 0
  url: env://

tpu:
  enabled: true
  num_cores: 8

data:
  train:
    type: hdf5
    dir: /dfdc/data
    chunks: 0 - 50
    dir_list: ''
    sample:
      frames: 10
      min_size: 38
      real_fake_ratio: 3.33
      sparse_frames_prob: 0.5
    # loader setting are per each GPU
    loader:
      batch_size: 16
      workers: 1
  val:
    type: hdf5
    dir: /dfdc/data
    chunks: 0, 1, 28, 32, 43, 49
    sample:
      frames: 10
      min_size: 38
      real_fake_ratio: 3.33
      sparse_frames_prob: 1.0
    loader:
      batch_size: 16
      workers: 1

optimizer:
  step_interval: 1

train:
  skip: false
  epochs: 100
  epoch_length: 8000
  checkpoints:
    load: null
    base_dir: null
    interval_epoch: 1
    interval_iteration: 1000
    max_checkpoints: 100

validate:
  interval: 5

logging:
  model: false
  iter_freq: 50
